### ISSUE TITLE
Clarification: License (?)

### ISSUE THREAD

**Issue by tnsasse** [wikimedia/jquery.i18n#111]
Hi Guys,

I see that there are two LICENSE files in the repository: GPL and MIT. Which is correct?
And from my knowledge (may be wrong) you cannot have both, as GPL is in conflict with MIT.

Thanks for clarification!

**Comment by Nikerabbit** [comment]
Our jQuery libraries are dual-licensed: https://www.mediawiki.org/wiki/Milkshake
