### ISSUE TITLE
PLURAL not working for some languages

### ISSUE THREAD

**Issue by MusikAnimal** [wikimedia/jquery.i18n#125]
Apparently there are pluralization issues for language codes bs, hr and sr.

Bosnian for instance:

Message: `"num-languages": "$1 {{PLURAL:$1|jezik|jezika}}"`
In the JavaScript console:
```
$.i18n('num-languages', 115);
=> "115 jezik"
```

When it should be `115 jezika`.

If you need a go-to for Bosnian, @srdjanm has offered to help. They said the [plural rules](https://github.com/wikimedia/jquery.i18n/blob/master/src/jquery.i18n.language.js#L39-L42) look correct, so maybe it's something else.

Thanks!

**Comment by Nikerabbit** [comment]
In your code example you did not provide the second value as parameter.

**Comment by MusikAnimal** [comment]
Sorry! My mistake, I updated it so that PLURAL uses $1, for simplicity. Same issue applies.

**Comment by Nikerabbit** [comment]
```
$.i18n().load( { 'num': "$1 {{PLURAL:$1|jezik|jezika}}" }, 'sr' );
Object {}
$.i18n('num', 115);
"115 jezika"
```

Are you setting the language to use correctly?

**Comment by MusikAnimal** [comment]
I was told the same issue applied to `sr` and `hr`, but any rate the example above was for `bs`.

**Comment by MusikAnimal** [comment]
Actually, I tried the same code as you for `sr` and I still get `jezik`. Clearly I'm doing something wrong :/ I copied over the newest versions of all the files. I do not have a `sr.json`, though, so it is falling back to another language. This apparently caused the same error explained in #105, so I re-added my "workaround":
```
if ( typeof pluralRuleParser === 'undefined' ) {
  return pluralFormIndex;
} else if ( pluralRuleParser( pluralRules[ pluralForms[ i ] ], number ) ) {
  return pluralFormIndex;
}
```
in place of https://github.com/wikimedia/jquery.i18n/blob/master/src/jquery.i18n.language.js#L331-L333. This may be why your example using `sr` isn't working for me.

**Comment by MusikAnimal** [comment]
So all this time (since January 2016) I have not been sourcing the CLDRPluralRuleParser!!! I wrongfully assumed everything I needed was in jquery.i18n's /src directory. I should have paid closer attention to the examples... but I do think we could maybe improve the README some so it's more clear what all is required for the framework to do its job. I'll try make a PR for that soon.

@Nikerabbit First, maybe you could clarify the necessity of the files? For instance the demos don't appear to source [jquery.i18n.emitter.bidi](https://github.com/wikimedia/jquery.i18n/blob/master/src/jquery.i18n.emitter.bidi.js). Under what conditions is this needed? That aside, it looks like all other files in /src are required, optionally hand-picking the files in /src/languages if you know you're only going to support certain languages. Is that accurate?

I'll go ahead a close this since the reported issue has been finally resolved. It hurts to think all this time PLURAL wasn't working for some languages!

**Comment by nemobis** [comment]
cc @santhoshtr too for the README
