### ISSUE TITLE
Errors with minified version

### ISSUE THREAD

**Issue by sashberd** [wikimedia/jquery.i18n#130]
Hi
First of all great job, very nice and useful plugin!
In my application I using Grunt with grunt uglify. 
All looks good, but on load I got a lot of ajax error on cosole.
After deep investigation I found that inside function load in for in loop it takes Array.prototype functions and pushes them inside ajax load urls:
![image](https://cloud.githubusercontent.com/assets/11975561/25897933/8fc3f646-3592-11e7-94b5-e984eadbe277.png)

On debug mode you can see that array length is 1, but the code continue to take prototype function:
![image](https://cloud.githubusercontent.com/assets/11975561/25897910/76b27a4c-3592-11e7-9666-54e549f9d700.png)
The result is many errors in console of ajax failed requests:
![image](https://cloud.githubusercontent.com/assets/11975561/25898007/e7765578-3592-11e7-81aa-e772a82d0d83.png)
I around the array prototype functions on the PS.
I found that if I replace for in to array.foreach this problem is not happend

```
// for ( locIndex in fallbackLocales ) {
                // 	fallbackLocale = fallbackLocales[locIndex];
                // 	sourceMap[fallbackLocale] = source + '/' + fallbackLocale + '.json';
                // }
				
                fallbackLocales.forEach(function(locale) {
                    sourceMap[fallbackLocale] = source + '/' + locale + '.json';
                });
```
For your review

**Comment by sashberd** [comment]
I see you fixed an issue
When will you release 1.0.5? 
I would like to use it?

**Comment by Nikerabbit** [comment]
We haven't done releases in a while. Should probably do it.
