### ISSUE TITLE
Attach an event handler function for on language change?

### ISSUE THREAD

**Issue by eflyjason** [wikimedia/jquery.i18n#151]
Is it possible to use something like 

```
$( document ).on( "language-change", function() {
    console.log( "Language just changed." );
});
```

to detect language change so that I can make corresponding changes to the interface's UI? Thanks! :)

**Comment by Nikerabbit** [comment]
This library itself doesn't change language. Usually you use something like jquery.uls library to provide language choose for the user. It provides onSelected callback, where you would tell jquery.i18n what language to use, and any other changes you want to do.

**Comment by eflyjason** [comment]
Understood. Thanks 👍
