### ISSUE TITLE
'jquery.i18n' is not in the npm registry.

### ISSUE THREAD

**Issue by davidbarratt** [wikimedia/jquery.i18n#154]
When I try to install with NPM I get the following error:
> Not Found
> 
> 'jquery.i18n' is not in the npm registry.
> You should bug the author to publish it

This issue exists to "bug the author to publish it"

**Comment by llech** [comment]
Any updates on this? There's a project https://www.npmjs.com/package/jquery-i18n?activeTab=versions but it doesn't look like it is maintained...

**Comment by Nikerabbit** [comment]
I don't know who that person is and whether that means that name is now permanently reserved for his work.

**Comment by davidbarratt** [comment]
I think `jquery.i18n` !== `jquery-i18n` but a maintainer of this repo would have to attempt to [publish it to npm](https://docs.npmjs.com/cli/publish) to find out. :)

**Comment by Malspherus** [comment]
Any updates on this?

**Comment by Nikerabbit** [comment]
There is no need to ask, we will keep the task updated if there are updates.

To set expectations, this library is **currently** in passive maintenance mode, which means we will only fix blocker issues, or issues that relate to other work, or simple changes that a developers might do quickly, outside planned work, based on their interest.

**Comment by santhoshtr** [comment]
I tried publishing. But it has name conflicts
```
npm notice
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! Package name too similar to existing packages; 
```

**Comment by samwilson** [comment]
It's now called `@wikimedia/jquery.i18n` and can probably be registered.

**Comment by santhoshtr** [comment]
I don't have credentials for @wikimedia org in npm.org. Do you know who has it? They can publish this to https://www.npmjs.com/org/wikimedia

**Comment by samwilson** [comment]
@jdforrester might know. Or can maintainers of other packages in the org add new ones? In which case maybe @davidbarratt can.

**Comment by davidbarratt** [comment]
Done.
https://www.npmjs.com/package/@wikimedia/jquery.i18n

@santhoshtr hopefully @jdforrester can give you access. After you create a new release (with `npm version`) and tag/push it with git, be sure to do `npm publish` to update npm with the new version. :)

**Comment by davidbarratt** [comment]
@samwilson thanks for pushing this forward! :)

**Comment by Dharmendra205111014** [comment]
Can anyone update doc with **how to use with npm registry**, it get difficult to figure out what are file need to import and how to get $.i18n available
