### ISSUE TITLE
Best practice for input placeholder values?

### ISSUE THREAD

**Issue by JohnMcLear** [wikimedia/jquery.i18n#157]
Currently I'm iterating over all inputs and doing ``$(this).attr( "placeholder" , $.i18n(key) );``

I'm getting key from the data-i18n value.

Is there a better method for setting an input type placeholder or is my approach okay?

**Comment by Nikerabbit** [comment]
That sounds like the best option as of now given (if I still remember correctly) that we don't have any explicit support for translating attribute values.

**Comment by JohnMcLear** [comment]
Okay great, thanks!  Worth popping in README maybe.
