### ISSUE TITLE
zh-hk does not fallback to zh, etc.

### ISSUE THREAD

**Issue by MusikAnimal** [wikimedia/jquery.i18n#158]
I noticed that with [Intuition](https://github.com/Krinkle/Intuition), zh-hk will fallback to zh, and similar for other regional variants. Was this intentionally left out of [jquery.i18n.fallbacks.js](https://github.com/wikimedia/jquery.i18n/blob/master/src/jquery.i18n.fallbacks.js)?

Most of my tools use Intuition to have translations on page load, then use jQuery.i18n for everything else. A lot of time has passed, and no one has said anything about zh showing up instead of zh-hk.

Pageviews Analysis in particular depends heavily on jQuery.i18n, and some messages aren't being shown because the fallback isn't there, even though zh translations exist: https://tools.wmflabs.org/pageviews?uselang=zh-hk

If it's a matter of the fallbacks simply missing, I will happily create a pull request :)

**Comment by santhoshtr** [comment]
I think this was missed from  jquery.i18n.fallbacks.js unintentionally. jquery.i18n's fallback mechanism is simple,  If `x=[s,r,t]`, it goes through s, r, t and finally to default fallback language (that is english). But if `t=[a]`, jquery.i18n still won't resolve x to a. 

One can argue that fallback mechanism should be smart enough for this. But adding entries to the array is trivial to get the required result. In this case `'zh-hk': [ 'zh-hant', 'zh-hans','zh' ]` does the trick

So yes, a pull request would be helpful here,

**Comment by MusikAnimal** [comment]
Sorry, I think I've got this wrong! I looked at Intuition's [fallback.json](https://github.com/Krinkle/intuition/blob/master/language/fallbacks.json), and it is near identical. This leads me to believe your fallback settings are probably correct, because I'm seeing the right fallbacks when I use Intuition.

I also told you the wrong thing. Pageviews Analysis doesn't have a zh.json, it has a zh-hans.json, which is what should be used when zh-hk doesn't exist. jQuery.i18n seems to specify this already.

It seems I have to load the fallback language manually? So I have the code, where `lang` is the requested langauge retrieved from the HTTP headers (in our case `zh-hk`):
```javascript
$.i18n({
  locale: lang
}).load({
  [lang]: `/pageviews/messages/${lang}.json`
}).then(
  ... start the application ...
);
```
I think jQuery.i18n knows it's supposed to fallback to `zh-hans` when a message for `zh-hk` doesn't exist, but it doesn't know where to look because I didn't tell it where `zh-hans` was.

So looks like this is my fault... sorry for the noise! I can't believe I did this wrong all this time. Thanks for your help, nonetheless!

Maybe when I have the free time, I can submit a PR for a function where you can give it the locale and a directory, and it will load all the necessary files for you. I think this is how Intuition does it.
