### ISSUE TITLE
New release? (v1.0.5)

### ISSUE THREAD

**Issue by jdforrester** [wikimedia/jquery.i18n#164]
Any chance of a new release? Especially with #163 it'd be nice to get the 72 commits merged since late 2015 into VisualEditor. :-)

**Comment by santhoshtr** [comment]
Prepare for version 1.0.5 release #167

**Comment by santhoshtr** [comment]
Done. https://github.com/wikimedia/jquery.i18n/releases/tag/v1.0.5

**Comment by jdforrester** [comment]
Thank you! I've made pull-throughs for [MediaWiki](https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/447818) and [VisualEditor](https://gerrit.wikimedia.org/r/c/VisualEditor/VisualEditor/+/447817).
