### ISSUE TITLE
Please update documentation

### ISSUE THREAD

**Issue by ivanromakh** [wikimedia/jquery.i18n#169]
In documentation there is underscore in keys
message_hello
this not working can you replace it with dash instead
$('selector').i18n() -> didn`t show me translation when I used underscore. 
Thanks for such cool library I will give it a star:)
Please:)

**Comment by phivk** [comment]
I'm adding to this issue to prevent duplicates.
@santhoshtr please comment if you'd prefer separate issues for additional documentation items.

Another thing missing from the documentation is the ability to render HTML markup inside message strings via the `data-i18n` method by prepending `[html]` to the message key like this:

```
data-i18n="[html]fillafulla-lead"
```

Would be great to add this to the documentation.
