### ISSUE TITLE
Fallback from de-DE to de

### ISSUE THREAD

**Issue by desmeit** [wikimedia/jquery.i18n#184]
```
  i18next.use(i18nextXHRBackend);
	  i18next.init({
		 			debug: true,
					lng: 'de-DE', // evtl. use language-detector https://github.com/i18next/i18next-browser-languageDetector
				
					fallbackLng: 'en',
					backend: {
					  loadPath: 'languages/{{lng}}.json'
					}
```

This is working but I'm wondering about the following behavior: First it looks for de-DE.json, then for de.json and then for en.json. How can I disable or edit the looking for de.json?

**Comment by MarcoAurelioWM** [comment]
Per @santhoshtr. Issue looks unrelated to this repository.
