### ISSUE TITLE
Translations in HTML not working?

### ISSUE THREAD

**Issue by lhrmota** [wikimedia/jquery.i18n#185]
Hi everyone.
I was trying to translate static elements in my pages, like labels and titles.

As far as I understand, it wouldn't even require explicit html, since I could use data-i18n, but this isn't working, probably my mistake.

I am reading the language setting from a cookie before the page loads and, as it is, $.i18n().locale has the value pt.

I have a translation-pt.json file like:
{
	(...)
	"kodi-address":"Endereço Kodi:",
(...)
}

 I insert an element on my page like this:
<div class="form-group">
    <label for="kodiAddress" data-i18n="kodi-address">Kodi address:</label>
    <input class="form-control" type="text" id="kodiAddress" value="localhost">
  </div>

Unfortunately, the label is not being translated... Am I getting something wrong?

Bye and thanks, Luís

**Comment by lhrmota** [comment]
I think I got this..

I have to call $('body').i18n();, right?

Luís

**Comment by ies1** [comment]
yes

here a link to an easy tutorial
https://phraseapp.com/blog/posts/jquery-i18n-the-advanced-guide/
