### ISSUE TITLE
JavaScript runtime error: Object doesn't support property or method 'split'

### ISSUE THREAD

**Issue by CaoMengLong** [wikimedia/jquery.i18n#186]
hi 👍  jquery.i18n  is great, i need help, think you!

i am use jquery.i18n in my cordova project.  build run it,  it's throw this error:
`Unhandled exception at line 51, column 5 in ms-appx-web://com.hitachi.eassy/www/js/lib/jquery.i18n.js
0x800a01b6 - JavaScript runtime error: Object doesn't support property or method 'split'`

jquery.i18n.js   in 57 line : 
while ( locale ) {
				// Iterate through locales starting at most-specific until
				// localization is found. As in fi-Latn-FI, fi-Latn and fi.
				localeParts = locale.split( '-' );             //    <-----error is here                        
				localePartIndex = localeParts.length;

**Comment by santhoshtr** [comment]
It seems the `locale` value is not a string? It is expected to be a string value. what did you pass?

**Comment by CaoMengLong** [comment]
> It seems the `locale` value is not a string? It is expected to be a string value. what did you pass?

Sorry, it was my fault. I sent in the wrong  `locale` value.
like  'ja' to 'jp' .   
Thank you very much. This problem can be closed.
