### ISSUE TITLE
pluralRuleParser is not defined

### ISSUE THREAD

**Issue by milyyy** [wikimedia/jquery.i18n#192]
I had cloned this demo,but it happened 'pluralRuleParser is not defined' open in brower.

**Comment by santhoshtr** [comment]
Did you do `git submodule update --init` as the README explains?
That will download the plural parser to lib folder.

**Comment by milyyy** [comment]
> Did you do `git submodule update --init` as the README explains?
> That will download the plural parser to lib folder.
Thank you. 
Has been solved
