### ISSUE TITLE
[Feature Request] Support for comments(//) in the localization files

### ISSUE THREAD

**Issue by thepra** [wikimedia/jquery.i18n#199]
In the present version both single line comments and inline comments in any `language.json` file produce parsing errors after `&.i18n().load(...)`(if debug is set to true).

Comment's, both in single-line and inline would be really useful to keep track from which *.js module/s comes from that string/s.

**Comment by santhoshtr** [comment]
Comments are not allowed in json- such a json is not a valid json. 

A practice that we follow in wikipedia is prefixing an identifier of the module, feature in the message key. For example: "modulename-feature-xxxxx-yyyyy-zzzzzz"
This may help in grepping in the source code as well.

**Comment by amire80** [comment]
Indeed. Comments just cannot be used in JSON.

Writing readable and relevant message keys is supposed to help with documentation, and most importantly, the documentation should be in the qqq file.
