### ISSUE TITLE
Support using Intl.PluralRules instead of CLDRPluralRuleParser

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/jquery.i18n#205]
For projects looking to adopt this in progressive web apps that work in modern browsers only, it would be very attractive to offer wikimedia/banana-i18n as a viable option without the need to bundle [CLDRPluralRuleParser.js](https://github.com/santhoshtr/CLDRPluralRuleParser) as well.

[Intl.PluralRules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules) exists now, which has reached Stage 4 for inclusion in ECMAScript 2020, and all major browsers have already implemented and shipped it as of a few months ago (including Node.js 10, ref https://github.com/wikimedia/jquery.i18n/issues/83).

**Comment by santhoshtr** [comment]
Done https://github.com/wikimedia/banana-i18n/commit/61b0b9cddcc2f06f440a8e3480ae5273dcb7b999

I am not planning to do similar changes in jquery.i18n unless there is a strong reason. jquery.i18n is supposed to be replaced by banana-i18n.

**Comment by Krinkle** [comment]
Thanks. I thought that repo was a fork that would eventually be merged into here as a pull request and then the repo name updated (GitHub supports renames with redirects etc).

That way we would preserve history of commits, issues, pull requests, comments etc.

But I see that banana-i18n is now no longer a fork but re-created as repo with no history beyond Nov 2018.
