### ISSUE TITLE
Load whole directory structure.

### ISSUE THREAD

**Issue by Lapotor** [wikimedia/jquery.i18n#221]
Hello,

is it possible to load a complete directory and it's sub directories?
Like:
```javascript
$.i18n().load( {
  en: 'i18n/en/'
});
```

**Comment by santhoshtr** [comment]
No. it is not possible to get all files in directory. It is not possible do using web fetch apis, a limitation independent of jquery.i18n. Please refer documentation for different ways a localization file can be used.
