### ISSUE TITLE
Failed in opening demo index page due to Chrome CORS policy.

### ISSUE THREAD

**Issue by StephenHuge** [wikimedia/jquery.i18n#241]
# Env
macOS BigSur 11.6.7
Chrome 103.0.5060.134 (x86_64)

# Problem
After pulling the project to local, I failed at using Chrome to open demo page, errors can be seen in the image below.
![image](https://user-images.githubusercontent.com/22100893/180955339-1c509678-ac83-4f94-afd0-5324b6d8301a.png)

**Comment by santhoshtr** [comment]
I see that you opened the HTML file using browser. This behaviour is expected in that case. Would it be possible to access it using a webserver? From the jquery.i18n , running `python -m http.server` would start a static webserver and you can navigate to the demo and it would work then. (There are many other ways to serve files using webserver -this is just an example)

**Comment by StephenHuge** [comment]
> I see that you opened the HTML file using browser. This behaviour is expected in that case. Would it be possible to access it using a webserver? From the jquery.i18n , running `python -m http.server` would start a static webserver and you can navigate to the demo and it would work then. (There are many other ways to serve files using webserver -this is just an example)

Yeah, I have found solution like what you said. I want to submit a pull request to fulfill this case making this quick-start more user-friendly, is that feasible？
