### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by reedy** [wikimedia/jquery.i18n#244]
https://github.com/wikimedia/jquery.i18n/compare/v1.0.7...master

Bit overdue on time, but looks like 1.0.8 is probably fine...

**Comment by jdforrester** [comment]
Let's? Yeah, 1.0.8 seems fine. I guess technically we dropped node 8 and 10 support (at least in guarantees — we were testing in node 8, now testing in 12/14/16), but that's well-post EOL stuff.

The only contentful change was the `sr-cyrl` addition.

**Comment by reedy** [comment]
CLDRPluralRuleParser in here seems to be a rather old version https://github.com/santhoshtr/CLDRPluralRuleParser/tree/8baf9aedc428924fe6ee508b3d952cb5564efb3a from October 2017..

https://github.com/santhoshtr/CLDRPluralRuleParser/compare/8baf9aedc428924fe6ee508b3d952cb5564efb3a...v1.4.0 (head of master is the same commit)

**Comment by jdforrester** [comment]
> CLDRPluralRuleParser in here seems to be a rather old version https://github.com/santhoshtr/CLDRPluralRuleParser/tree/8baf9aedc428924fe6ee508b3d952cb5564efb3a from October 2017..
> 
> [santhoshtr/CLDRPluralRuleParser@8baf9ae...v1.4.0](https://github.com/santhoshtr/CLDRPluralRuleParser/compare/8baf9aedc428924fe6ee508b3d952cb5564efb3a...v1.4.0) (head of master is the same commit)

Hmm, yes, we should bump; MW is using https://github.com/santhoshtr/CLDRPluralRuleParser/commit/0dda851 FWIW.

**Comment by f1liu** [comment]
When will v1.0.8 this version be officially released? @jdforrester

**Comment by zjyrfry** [comment]
When will v1.0.8 be released? @jdforrester

**Comment by zjyrfry** [comment]
When will v1.0.8 this version be officially released? @jdforrester @reedy

**Comment by jdforrester** [comment]
> When will v1.0.8 this version be officially released? @jdforrester

Well, someone has to approve #245 first. :-)

**Comment by zjyrfry** [comment]
Okay, first of all, thank you for your reply.Because I urgently need to use the new version, hope someone approve it ，then release the new version as soon as possible.

**Comment by zjyrfry** [comment]
> > When will v1.0.8 this version be officially released? @jdforrester
> 
> Well, someone has to approve #245 first. :-)

Okay, first of all, thank you for your reply.Because I urgently need to use the new version, hope someone approve it ，then release the new version as soon as possible.

**Comment by Abijeet** [comment]
> > > When will v1.0.8 this version be officially released? @jdforrester
> > 
> > 
> > Well, someone has to approve #245 first. :-)
> 
> Okay, first of all, thank you for your reply.Because I urgently need to use the new version, hope someone approve it ，then release the new version as soon as possible.

The Wikimedia language team has this on [its radar](https://phabricator.wikimedia.org/T334731). Expect a release soon. Hopefully early next week.
