### ISSUE TITLE
Can I use i18n for DOM attrs like title or placeholder?

### ISSUE THREAD

**Issue by hustcer** [wikimedia/jquery.i18n#65]
Can I use i18n for DOM attrs like title or placeholder without using JS to change it's attribute? for example:

``` html
<div class="content">
 <input type="text" placeholder="translate me" title="translate me">
</div>
```

How can I use: 

``` javascript
$('div.content').i18n();
```

To update the translated messages for placeholder or title?

**Comment by alansutherland** [comment]
There's a much simpler way to add translations for placeholders that the creator of jQuery i18n recommends

`<input data-i18n="[placeholder]name" value="name">`

and then in your translation.json file

`"name" : "Name"`

https://stackoverflow.com/questions/22728797/translate-custom-attributes-with-i18next-placeholder-value

**Comment by HusseinElGanzory** [comment]
> There's a much simpler way to add translations for placeholders that the creator of jQuery i18n recommends
> 
> `<input data-i18n="[placeholder]name" value="name">`
> 
> and then in your translation.json file
> 
> `"name" : "Name"`
> 
> https://stackoverflow.com/questions/22728797/translate-custom-attributes-with-i18next-placeholder-value

best and simple solution thanks

**Comment by rene-guerrero** [comment]
> There's a much simpler way to add translations for placeholders that the creator of jQuery i18n recommends
> 
> `<input data-i18n="[placeholder]name" value="name">`
> 
> and then in your translation.json file
> 
> `"name" : "Name"`
> 
> https://stackoverflow.com/questions/22728797/translate-custom-attributes-with-i18next-placeholder-value

Save me lot of time 👍👍👍

**Comment by JustineMiko** [comment]
> > There's a much simpler way to add translations for placeholders that the creator of jQuery i18n recommends
> > `<input data-i18n="[placeholder]name" value="name">`
> > and then in your translation.json file
> > `"name" : "Name"`
> > https://stackoverflow.com/questions/22728797/translate-custom-attributes-with-i18next-placeholder-value
> 
> Save me lot of time

Hi, i have tried this one but in my searchbar i can't write any entry after doing this :(
